name: linter_check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run_linter
        run: |
          pip install poetry
          make install
          make init
